#!/bin/sh

case "$1" in
    start)
        echo "Starting jitterentropy-rngd"
        /usr/sbin/jitterentropy-rngd &
        ;;
    stop)
        echo "Stopping jitterentropy-rngd"
        killall jitterentropy-rngd
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
