#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

set_mmc() {
	mmc=/sys/devices/platform/jzmmc_v1.2.$1/present
	[ "$(cat $mmc)" = "N" ] && echo "INSERT" > $mmc
}

case "$1" in
	# Generic ATBM603X
	atbm603x-generic)
		set_mmc 1
		cp -f /usr/share/atbm60xx_conf/atbm_txpwer_dcxo_cfg.txt /tmp
		cp -f /usr/share/atbm60xx_conf/set_rate_power.txt /tmp
		modprobe atbm603x_wifi_sdio atbm_printk_mask=0
		;;

	# Generic RTL8189FS
	rtl8189fs-generic)
		set_mmc 1
		modprobe 8189fs
		;;

	# Generic XR829
	xr829-generic)
		modprobe xradio_wlan
		;;

	# T20 Wyze PanV1
	rtl8189es-t20-wyze-pan-v1)
		set_mmc 1
		modprobe 8189es rtw_power_mgnt=0 rtw_enusbss=0
		;;

	# T20 Wyze V2
	rtl8189ftv-t20-wyze-v2)
		set_mmc 1
		modprobe 8189fs rtw_power_mgnt=0 rtw_enusbss=0
		;;

	# T31 Wyze DB3
	rtl8189ftv-t31-wyze-db3)
		set_mmc 1
		modprobe 8189fs rtw_power_mgnt=0 rtw_enusbss=0
		;;

	# T31 Wyze PanV2
	atbm603x-t31-wyze-pan-v2)
		set_gpio 58 0
		set_gpio 58 1
		set_mmc 1
		cp -f /usr/share/atbm60xx_conf/atbm_txpwer_dcxo_cfg.txt /tmp
		cp -f /usr/share/atbm60xx_conf/set_rate_power.txt /tmp
		modprobe atbm603x_wifi_sdio atbm_printk_mask=0
		;;

	# T31 Wyze V3 / AtomCam 2
	atbm603x-t31-wyze-v3)
		set_gpio 57 0
		set_gpio 57 1
		set_mmc 1
		cp -f /usr/share/atbm60xx_conf/atbm_txpwer_dcxo_cfg.txt /tmp
		cp -f /usr/share/atbm60xx_conf/set_rate_power.txt /tmp
		modprobe atbm603x_wifi_sdio atbm_printk_mask=0
		;;

	# T31 Wyze V3
	rtl8189ftv-t31-wyze-v3)
		set_gpio 57 1
		set_mmc 1
		modprobe 8189fs rtw_power_mgnt=0 rtw_enusbss=0
		;;

	*)
		echo "Unsupported device: $1"
		exit 1
		;;
esac


exit 0
