#!/bin/sh

set_gpio() {
	[ "$2" -eq 1 ] && gpio set $1 || gpio clear $1
	sleep 1
}

case "$1" in
	# Generic MT7601U
	mt7601u-generic)
		modprobe mt7601u
		;;

	# Generic RTL8188EU
	rtl8188eu-generic)
		modprobe 8188eu
		;;

	# Generic RTL8188FU
	rtl8188fu-generic)
		modprobe 8188fu
		;;

	# Generic RTL8733BU
	rtl8733bu-generic)
		modprobe 8733bu
		;;

	# Generic RTL8811CU
	rtl8811cu-generic)
		modprobe 8821cu
		;;

	# Generic RTL8812AU
	rtl8812au-generic)
		modprobe 88XXau rtw_ht_enable=0 rtw_led_enable=0
		;;

	# Generic ATBM603x
	atbm603x-generic-usb)
		modprobe atbm603x_wifi_usb
		;;

	# GK7205V200 CamHi
	mt7601u-gk7205v200-camhi)
		set_gpio 9 0
		modprobe mt7601u
		;;

	# GK7205V300 CamHi
	mt7601u-gk7205v300-camhi)
		devmem 0x100C0080 32 0x530
		set_gpio 7 0
		modprobe mt7601u
		;;

	# GK7205V200 CamHi
	rtl8733bu-gk7205v200-camhi)
		set_gpio 9 0
		modprobe 8733bu
		;;

	# GK7205V200 Kafei
	8188fu-gk7205v200-kafei)
		set_gpio 57 0
		modprobe 8188fu
		;;

	# GK7205V300 CamHi
	rtl8733bu-gk7205v300-camhi)
		devmem 0x100c0080 32 0x0
		set_gpio 7 0
		modprobe 8733bu
		;;

	# GK7205V300 XM IVG-G6S
	atbm603x-gk7205v300-xm-g6s)
		devmem 0x100C0080 32 0x530
		set_gpio 7 0
		modprobe atbm603x_wifi_usb
		;;

	# GK7205V300 Vase
	rtl8811cu-gk7205v300-vase)
		devmem 0x100c0080 32 0x0
		set_gpio 7 1
		modprobe 8821cu
		;;

	# HI3516EV200 CamHi
	mt7601u-hi3516ev200-camhi)
		set_gpio 9 0
		modprobe mt7601u
		;;

	# HI3516EV300 CamHi
	mt7601u-hi3516ev300-camhi)
		devmem 0x100C0080 32 0x530
		set_gpio 7 0
		modprobe mt7601sta
		;;

	# HI3518EV100 CamHi
	mt7601u-hi3518ev100-camhi)
		modprobe mt7601sta
		;;

	# HI3518EV200 LifeSmart
	rtl8188fu-hi3518ev200-lifesmart)
		set_gpio 54 1
		modprobe 8188fu
		;;

	# HI3518EV200 Switcam HS303 (V1)
	rtl8188fu-switcam-hs303)
		set_gpio 3 1
		modprobe 8188fu
		;;

	# HI3518EV200 Lenovo Snowman 1080p
	rtl8188eus-hi3518ev200-lenovo)
		devmem 0x200f006c 32 0
		modprobe 8188eu
		;;

	# HI3518EV200 Qtech QVC-IPC-136W
	rtl8188eu-hi3518ev200-qvc-ipc-136w)
		set_gpio 7 1
		modprobe 8188eu
		;;

	# HI3518EV200 Switcam HS303 V2
	rtl8188eus-switcam-hs303v2)
		set_gpio 54 1
		modprobe 8188eu
		;;

	# HI3518EV300 Unknown1
	rtl8188fu-hi3518ev300-unknown1)
		set_gpio 57 0
		modprobe mac80211
		modprobe 8188fu
		;;

	# HI3518EV300 t5810hct-m02
	rtl8188fu-hi3518ev300-t5810hct-m02)
		set_gpio 40 1
		modprobe 8188fu
		;;

	# SSC325DE IMOU C22EP-S2
	rtl8188fu-ssc325de-imou-c22ep-s2)
		set_gpio 62 1
		modprobe 8188fu
		;;

	# SSC335DE IMOU C22E-S2 V2
	rtl8188fu-ssc335de-imou-c22e-s2-v2)
		set_gpio 14 0
		modprobe 8188fu
		;;

	# SSC333 Babysense See HD IP206
	rtl8188fu-babysense-see-hd-ip206)
		set_gpio 14 1
		modprobe 8188fu
		;;

	# SSC333 Meari Speed 6S
	rtl8188fu-ssc333-meari-speed-6s)
		set_gpio 14 1
		modprobe 8188fu
		;;

	# SSC333 Tapo C110
	ssw101b-ssc333-tapo-c110)
		set_gpio 16 1
		modprobe ssw101b_wifi_usb
		;;

	# SSC333 Tapo C110 v2.6
	atbm6012b-ssc333-tapo-c110)
		set_gpio 16 1
		modprobe atbm6012b_wifi_usb
		;;

	# SSC335DE Uniview C1L-2WN-G
	rtl8188fu-ssc335de-uniview-c1l-2wn-g)
		set_gpio 1 0
		modprobe 8188fu
		;;

	# SSC337DE BroadbandService
	aic8800-ssc337de-broadband)
		modprobe aic8800_fdrv
		;;

	# SSC337DE BroadbandService
	rtl8188fu-ssc337de-broadband)
		set_gpio 2 0
		modprobe 8188fu
		;;

	# SSC337DE Foscam
	rtl8188fu-ssc337de-foscam)
		set_gpio 15 0
		modprobe 8188fu
		;;

	# SSC377 Dahua
	ssv6x5x-ssc377-dahua)
		set_gpio 10 1
		modprobe ssv6x5x
		;;

	# T10 NVT
	mt7601sta-t10-nvt)
		modprobe cfg80211
		modprobe mt7601sta
		;;

	# T21 BJS
	rtl8188fu-t21-bjs)
		set_gpio 50 0
		modprobe 8188fu
		;;

	# T21 Smartwares
	rtl8188fu-t21-smartwares)
		set_gpio 49 1
		modprobe 8188fu
		;;

	# T31 Aoni EP01J05
	rtl8188fu-t31-aoni-ep01j05)
		set_gpio 43 1
		modprobe 8188fu
		;;

	# T31 Aosu C5L
	rtl8188fu-t31-aosu-c5l)
		set_gpio 43 0
		modprobe 8188fu
		;;

	# T31 CamHi
	mt7601u-t31-camhi)
		set_gpio 61 0
		modprobe mac80211
		;;

	# T31 Camhipro
	rtl8733bu-t31-camhipro)
		set_gpio 61 0
		modprobe 8733bu
		;;

	# T31 iFlytek
	ssv6155-t31-iflytek)
		set_gpio 10 1
		modprobe ssv6155
		;;

	# T31 iFlytek XFP301-M
	rtl8188fu-t31-iflytek-xfp301m)
		set_gpio 10 1
		modprobe 8188fu
		;;

	# T31 ZTE K540
	atbm603x-t31-zte-k540)
		set_gpio 51 0
		modprobe atbm603x_wifi_usb
		;;

	# T31 Aoni E97VJ62
	rtl8188fu-t31-aoni-e97vj62)
		set_gpio 53 1
		modprobe 8188fu
		;;

	*)
		echo "Unsupported device: $1"
		exit 1
		;;
esac


exit 0
